
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('../css/main.css'); ?>" />

<div id="header">
	
		<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
		 <a id="editprofile" href="

			<?php echo $this->url(

			 array(
			'controller' =>  'index',
	  		'action'  => 'profiles',

	  		)); ?>

	  ">profiles</a>
	<?php endif; ?>
	



	
		<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
		 <a id="editprofile" href="

			<?php echo $this->url(

			 array(
			'controller' =>  'index',
	  		'action'  => 'add-template',

	  		)); ?>

	  ">Templates</a>
	<?php endif; ?>



		<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
		 <a id="editprofile" href="

			<?php echo $this->url(

			 array(
			'controller' =>  'index',
	  		'action'  => 'news-letter',

	  		)); ?>

	  ">NewsLetter</a>
	<?php endif; ?>

		<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
		 <a id="inviteFriend" href="

			<?php echo $this->url(

			 array(
			'controller' =>  'index',
	  		'action'  => 'invite-friend',

	  		)); ?>

	  ">inviteFriend</a>


	<?php endif; ?>
		<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>

		 <a id="deleteme" href="<?php echo $this->Url(
                            array(
                            'controller' =>  'index',
                            'action'     =>  'members',
                            'id'         =>   '1',
                            )); ?>">Active Members</a>

	<?php endif; ?>

		<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>

		 <a id="deleteme" href="<?php echo $this->Url(
                            array(
                            'controller' =>  'index',
                            'action'     =>  'members',
                            'id'         =>   '0',
                            )); ?>">inactive Members</a>
	<?php endif; ?>
	
</div>